spring:
  application:
    name: goods-server
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sbsmdx;encrypt=false;
    username: test
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    

