spring:
  application:
    name: orders
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=orders;encrypt=false;
    username: test
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    register-with-eureka: true
    fetch-registry: false