spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: goods-server
          uri: lb://goods-server
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1

        - id: warehouse-server
          uri: lb://warehouse-server
          predicates:
            - Path=/warehouse/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': 
            allowed-origins:
            - "http://127.0.0.1:3000"
            allowed-methods:
            - "*"
            allowed-headers:
            - "*"
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8000
